### ISSUE TITLE
Big-R review that pipes to a pager shows raw escape codes

### ISSUE THREAD

**Issue by gorf2000** [michaelShriver/ircom#3]
If I am on libera chat and I press 'r' for review, everything looks fine

If I press 'R' and type 100 or something, all of the text is escaped, like the bolding around people's names, for example:

ESC[33;1m[08:08:19] peteyboy_ has joined #test.ESC[0m
ESC[33;1m[08:08:19] TOPIC: < rando> "One must beware of anyone who is both stupid and hardworking; he must not be entrusted with any responsibility because he will always only cause damage"ESC[0m

**Comment by michaelShriver** [comment]
Patched in https://github.com/michaelShriver/ircom/commit/639f11aa71659b31e7173f57204fa831641d0965
